# Generated by Django 3.1.7 on 2021-03-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismogram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterModelOptions(
            name='geometry',
            options={'verbose_name': 'Geometry', 'verbose_name_plural': 'Geometry'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='seismicdata',
            options={'verbose_name': 'SeismicData', 'verbose_name_plural': 'SeismicData'},
        ),
    ]
